#!/bin/bash

adb connect localhost
adb -s localhost shell su -c 'am start -n com.android.settings/.TetherSettings' 
sleep 1
adb -s localhost shell su -c 'input keyevent 20'
sleep 1                                                                                                      
adb -s localhost shell su -c 'input keyevent 20'     
sleep 1                                                                                                 
adb -s localhost shell su -c 'input keyevent 66'  
sleep 1                                                                                                    
adb -s localhost shell su -c 'input keyevent 20' 
sleep 1                                                                                                     
adb -s localhost shell su -c 'input keyevent 19' 
sleep 1                                                                                                     
adb -s localhost shell su -c 'input keyevent 66'